version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ramble_db
    restart: always
    environment:
      POSTGRES_USER: ramble
      POSTGRES_PASSWORD: ramble1234
      POSTGRES_DB: ramble_software
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: